### ISSUE TITLE
Timeout Error - Sense Nov 2022 ?

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler-sheet-icons#264]
### Discussed in https://github.com/ptarmiganlabs/butler-sheet-icons/discussions/261

<div type='discussions-op-text'>

<sup>Originally posted by **jsebright** December 13, 2022</sup>
Hi,  am trying to generate some files on a windows server that I've just upgraded to Nov 2022 release. Have got the commandline working enough so that it processes all the sheets, but after that I am getting a timeout error.

2022-12-13T09:34:44.939Z error: QSEoW APP: TimeoutError: Waiting for selector `.//*[@id="hub-sidebar"]/div[1]/div[1]/div/div/div` failed: Waiting failed: 30000ms exceeded

I get the same error on another server where I've managed to get it to run before, but have recently upgraded to Nov 2022 on that as well.
Have Qlik changed something on the hub page?</div>

**Comment by mountaindude** [comment]
This bug is indeed caused by the fact that Qlik has updated the hub. 
Which means there is new HTML in place, which means BSI will not find the HTML tags it looks for when trying to log out after generating thumbnail images for an app.

The planned solution is to introduce a new command line parameter `--sense-version`.
Via this parameter BSI will know which version the target Sense system is on and then look for the appropriate HTML codes.

Note that the above applies to QSEoW.
Qlik Cloud is easier - if Qlik changes something critical (from BSI's point of view) in the web frontend BSI will break. 
Once updated to handle the new Qlik Cloud frontend BSI will work again. No need for a new command line parameter.

**Comment by jsebright** [comment]
Thanks for finding this. We are at the mercy of Qlik's (seemingly) random changes. As you say on Cloud then everyone is on the same version so changes are perhaps easier to deal with but presumably more frequent.

**Comment by mountaindude** [comment]
Well, I would be more concerned if Qlik *didn't* made changes and updated the Sense client code base....
If anything it's been the same for quite some time, making the recent changes (2022-Nov) even overdue. 

Tools like BSI just have to find ways to adapt and become more generic - which is ultimately a good thing.

A new version of BSI is in the works. It supports multiple Sense versions and should thus be future safe - at least with respect to changing hub code.

**Comment by mountaindude** [comment]
The new command line option will most likely look something like this:

<img width="1195" alt="image" src="https://user-images.githubusercontent.com/1029262/210250551-73ef9775-911e-4f55-b864-236376d39b87.png">

This will require BSI users to double check which Sense version they are using and set the parameter accordingly. 

The alternative would be to automatically detect/check which Sense version is used. That would be error prone though, as there isn't a solid, publicly available way to determine Sense version using the APIs. 
Or maybe there is - having a command line parameter is easier to implement though.
