### ISSUE TITLE
Process finsihes saying it succeeded when it fails halfway through

### ISSUE THREAD

**Issue by WendellTruax** [ptarmiganlabs/butler-sheet-icons#285]
### What version of Butler Sheet Icons are you using?

3.0.0

### What command did you use to start Butler Sheet Icons?

.\butler-sheet-icons.exe qseow create-sheet-thumbnails --host qlik.host.com --prefix form --appid '1ae9b69e-774e-4e6c-a6da-2a086f89b643' --apiuserdir Internal --apiuserid sa_api --loglevel debug --logonuserdir Directory --logonuserid username --logonpwd password --contentlibrary 'Testing Butler Icons' --pagewait 5 --secure true --headless true --imagedir './img' --certfile ".\client.pem" --certkeyfile ".\client_key.pem" --includesheetpart 4 --sense-version "pre-2022-Nov"

### What operating system are you using?

Windows

### What CPU architecture are you using?

Not Sure

### What Qlik Sense versions are you using?

February 2022 Patch 1

### Describe the Bug

I have grabbed the standalone, setup a form based virtual proxy and it looks like it can connect. However when it starts to process the sheets in the application I get and error that says: "No element found for selector: username-input". Then afterwards the debug log says "Call to qseowCreateThumbnails succeeded: true" Which is not accurate since all it created is the image for the login page. Not sure what the problem is here since I added the user login information in the command.
Let me know what I am missing here.
<img width="510" alt="Butler Icon Error" src="https://user-images.githubusercontent.com/28932839/212792985-5b9dff49-36a1-4162-8f4e-22e8337951b3.PNG">

**Comment by mountaindude** [comment]
A couple of things come to mind.

1. Butler Sheet Icons (BSI) v3 was created to address the fact that client-managed Sense ver 2022-Nov changed things in the web frontend, breaking BSI. A new parameter `--sense-version` was then introduced to tell BSI which version the target Sense environment is running. Possible values are shown by adding the --help parameter when running BSI. But then again, you've already added that parameter, so this should not be a problem.
2. You mention having a new virtual proxy, sounds you know what you are doing. Still, looking at myself I've made more mistakes over the years than I can count... Things happen. To ensure that the correct login screen is presented to BSI you can try changing the `--headless` parameter to `false`. That will show the browser that BSI uses behind the scenes to do its work. This way you can ensure that BSI is presented with the expected login screen.

The error message "No element found for selector: username-input" indicate that BSI times out waiting for a login text box in the web interface. Point 2 above is your best bet investigating this, I'd say.

Finally, I won't rule out a bug in BSI of course. Always possible, but I'd test option 2 above first before digging deeper in the possible-bug track.

**Comment by mountaindude** [comment]
Should be fixed for sure in current version.
