### ISSUE TITLE
Hidden Sheet crashes BSI

### ISSUE THREAD

**Issue by cuthulino** [ptarmiganlabs/butler-sheet-icons#408]
### What version of Butler Sheet Icons are you using?

3.0.0

### What version of Node.js are you using? Not applicable if you use the standalone version of Butler Sheet Icons.

standalone

### What command did you use to start Butler Sheet Icons?

. .\modules\Butler-Sheet-Icons\butler-sheet-icons.exe qseow create-sheet-thumbnails --host <hostname> --certfile <fullpathToClient.pem> --certkeyfile <fullPathToClient_key.pem> --appid 01fb37ce-d92c-4b54-8657-92f614e8c004 --headless false --apiuserdir internal --apiuserid sa_api --prefix form --loglevel debug --logonuserdir <ourUserdir> --logonuserid <myUser> --logonpwd <password> --sense-version 2022-Nov

### What operating system are you using?

Windows 10

### What CPU architecture are you using?

x64

### What Qlik Sense versions are you using?

2023-May Patch 3

### Describe the Bug

A hidden sheet crashes bsi, because the wrapper is not found.
I observed it in headless = false mode.

![grafik](https://github.com/ptarmiganlabs/butler-sheet-icons/assets/4634522/88158455-637a-4e66-ba29-7588b429e848)

### Expected Behavior

bsi should ignore hidden sheets

### To Reproduce

Let bsi run on an app with a hidden sheet

**Comment by mountaindude** [comment]
Nice find.
On the todo-list.
