### ISSUE TITLE
Login to Qlik Sense cloud no longer works

### ISSUE THREAD

**Issue by mountaindude** [ptarmiganlabs/butler-sheet-icons#542]
### What version of Butler Sheet Icons are you using?

3.4.1

### What version of Node.js are you using? Not applicable if you use the standalone version of Butler Sheet Icons.

-

### What command did you use to start Butler Sheet Icons?

-

### What operating system are you using?

macOS

### What CPU architecture are you using?

-

### What Qlik Sense versions are you using?

-

### Describe the Bug

Looks like Qlik has change the HTML for the login page to QS Cloud. 
BSI cannot find the login input boxes on that page. 

Update BSI to work with current QS Cloud login.

**Comment by bskemp01** [comment]
does this mean any of the BSI versions wont make it past the login screen?

**Comment by mountaindude** [comment]
Indeed - at least any BSI version pre 3.5.0, which was released a few hours ago.
That version works nicely here at leas. 
I only have a EU tenant to test against, so I am slightly worried US tenants work differently.

There's also always a risk of Qlik rolling out changes over time, meaning that some tenants in theory could have one login scree, while other tenants have different html code on their login screens.

But do give 3.5.0 a spin - as mentioned it works nicely here, and also passes all test scenarios.

**Comment by mountaindude** [comment]
Fixed in version 3.5.0.

**Comment by bskemp01** [comment]
another question if i may, does this app take into account users with identity providers? i have yet to get this to work so i downloaded the node.js code and fiddled around with it. i can get it to run if i comment out the code looking for the login section. since my company computer uses my microsoft account to log into QLIK there usually isnt a login page in my browser.

**Comment by mountaindude** [comment]
Good question. 
Should prob clarify that in the Readme.

BSI has only been tested with regular Qlik account. 
2 factor logins will definitely not work, as BSI wont know the 2FA code.

You can run the tool with an option --headless false, to see what actions are actually carried out by BSI.

**Comment by mountaindude** [comment]
By "Qlik account" I mean an account that's present in the QS Cloud tenant. 

As a test, what happens if you open an incognito browser window and log in to QS Cloud with your account?

Are you redirected to some other login provider? If so BSI will not work.

Will add some examples re this in the readme.

**Comment by bskemp01** [comment]
when im in network, i.e. in the office, i dont need to use 2FA. i did use the headless false but the screen runs so quick i never get to see it lol. but i just assume its using my microsoft account to login. wasnt sure if there was a way to check for that in the code. but ill keep tinkering :)

**Comment by mountaindude** [comment]
@bskemp01  Here's an idea: 

What if we add a new command line option that makes BSI skip login to QS Cloud entirely?
Something like `--skip-login`. 
I would have to invent/implement some way of testing that though... Or create a test build that you can test?
It's a rather minor change, maybe 15-20 minutes of work or something like that.

I'll add a section to the readme too, covering various aspects of logging in.

**Comment by mountaindude** [comment]
@bskemp01 
3.6.0 was released earlier today, it includes the `--skip-login` flag. 
Basic testing of it is done, but until proven otherwise it's still a beta feature, I'd say.

**Comment by mountaindude** [comment]
@bskemp01 

Docs updated wrt `--skip-login`: https://github.com/ptarmiganlabs/butler-sheet-icons/tree/butler-sheet-icons-v3.6.0?tab=readme-ov-file#concepts-specific-to-qs-cloud

**Comment by bskemp01** [comment]
thanks for the update. im checking it out now
