### ISSUE TITLE
Cached browser not recognized. Trying to download new one.

### ISSUE THREAD

**Issue by cuthulino** [ptarmiganlabs/butler-sheet-icons#568]
### What version of Butler Sheet Icons are you using?

3.6.2

### Which version(s) of Butler Sheet Icons work for you?

3.1.0

### What version of Node.js are you using? Not applicable if you use the standalone version of Butler Sheet Icons.

v20.15.0

### What operating system are you using?

Windows Server

### What CPU architecture are you using?

64

### What Qlik Sense versions are you using?

2024-Feb P4

### Describe the Bug

Defining a browser to use from cache with `--browser-version` does ignore the cached one and tries to download a new one.

Listing the installed browser with `browser list installed` results in these two:
![image](https://github.com/ptarmiganlabs/butler-sheet-icons/assets/4634522/f2706a36-022d-47d7-9816-ff2c792ccb9a)
But none of the two Versions result in using the cached one.

![image](https://github.com/ptarmiganlabs/butler-sheet-icons/assets/4634522/b669887f-32f2-4055-a480-3b7b0ee8d0c4)

I am missing something or is this a strange behavior?
(I am running the node version of BS)

### Expected Behavior

The cached Browser should be used.
(worked in v3.1.0)

### To Reproduce

Call bsi with specific browser version.

**Comment by cuthulino** [comment]
Looks like it fails on `if (!canDownloadBrowser)`. ([link](https://github.com/ptarmiganlabs/butler-sheet-icons/blob/a74d084836eaedfb73be70b627d46364f804a069/src/lib/browser/browser-install.js#L83C9-L83C35))

I run bsi offline, if `canDownloadBrowser` does not return true when a cached version is found, bsi will always fail here on offline systems.

[canDownload](https://github.com/puppeteer/puppeteer/blob/866f72021c8bbbe94dea3c2e1853dd0182d61c7a/packages/browsers/src/install.ts#L338) from puppeteer looks like it is only checking online availability, not chached ones.

I would say, an earlier check for a cached version is needed here, what do you think?

**Comment by mountaindude** [comment]
Thanks for reporting this, sounds like you’ve stumbled upon a bug.
I am away from proper computers for some weeks now, will look into this
when I get a chance. Should be a reasonably easy fix if it’s indeed a bug.

Cheers
Göran

**Comment by mountaindude** [comment]
@cuthulino I have tried reproducing this but failed.

Using the same node version, samt BSI version, on Windows.
When I run BSI a second time it finds and uses the cached browser. 

Maybe something is broken in the cache on disk, have you tried emptying it?

```powershell
PS C:\code\butler-sheet-icons\src> node .\butler-sheet-icons.js browser uninstall-all
2024-08-23T13:11:54.187Z info: App version: 3.6.2
2024-08-23T13:11:54.202Z info: Starting uninstallation of all browsers
2024-08-23T13:11:54.202Z info: Uninstalling 1 browsers:
2024-08-23T13:11:54.202Z info:     Starting uninstallation of "chrome", build id "128.0.6613.85", platform "win64", path "C:\Users\goran\.cache\puppeteer\chrome\win64-128.0.6613.85"
2024-08-23T13:11:54.280Z info: Removing any remaining files and directories in the browser cache directory
2024-08-23T13:11:54.296Z info: Browser "chrome" (128.0.6613.85) uninstalled.
```

**Comment by mountaindude** [comment]
@cuthulino Forgot to ask, what exact command are you running?
That's relevant in order for me to try reproducing the error. Feel free to obfuscate sensitive info in the command/parameters of course.

**Comment by cuthulino** [comment]
Maybe it is because i never installed a Browser via the commandline? My Server has no Internet access and i can only copy and paste a chrome version from an online machine. 
I already did so before and it worked.

We already talked about this some time ago in an other issue.

Im in holiday for two Werks from today.
I can deliver the exactly command after the two weeks.

**Comment by mountaindude** [comment]
Ahhh, right. That probably explains it.
Offline use is not part of the test suite that BSI uses. 

Good that it worked and enjoy your vacation!
Closing this ticket as you got it working.

**Comment by cuthulino** [comment]
Sorry was on holidays...

I think you can reopen this. 
You misunderstood me.
It does not work for me at the moment.

On version 3.1.0 (that's what I got running at the moment) I can download the chromium browser manually on my online machine, move it into the cache folder of puppeteer on my offline servers and bsi works.

With the 3.6.2 Version this no longer works.

`browser list installed` lists the copied browser, but `--browser-version` just ignores the cached one and tries to download. 
What fails because there is no internet connection.





> @cuthulino Forgot to ask, what exact command are you running? That's relevant in order for me to try reproducing the error. Feel free to obfuscate sensitive info in the command/parameters of course.

This is the used command with the 3.10 Version:
```
node.exe 'C:\butler-sheet-icons\modules\butler-sheet-icons\butler-sheet-icons.js' qseow create-sheet-thumbnails --host redacted --certfile 'redacted path to .pem' --certkeyfile 'redacted path to .pem' --apiuserdir internal --apiuserid sa_api --loglevel debug --logonuserdir redacted--logonuserid redacted--logonpwd redacted# --prefix form --contentlibrary SheetPreviews --imagedir 'C:\butler-sheet-icons\images' --pagewait 10 --appid '7c39dc71-f524-49c9-9eeb-fed0e0e9c74b'--browser-version 117.0.5911.2 --sense-version 2023-May 
```
